services:

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - django_index_network

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=django_index_password
      - POSTGRES_DB=django_index
    networks:
      - django_index_network


networks:
  django_index_network:

volumes:
  db_data:
