# Generated by Django 5.1.3 on 2024-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductWithoutIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("clothing", "Clothing"),
                            ("home appliances", "Home Appliances"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_without_index",
            },
        ),
        migrations.CreateModel(
            name="ProductWithSingleIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(db_index=True, max_length=50)),
                ("price", models.IntegerField(db_index=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_with_single_index",
            },
        ),
        migrations.CreateModel(
            name="ProductWithCompositeIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("price", models.IntegerField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_with_composite_index",
                "indexes": [
                    models.Index(fields=["name"], name="product_wit_name_5adbb5_idx"),
                    models.Index(
                        fields=["category", "price"], name="category_price_idx"
                    ),
                ],
            },
        ),
    ]
